/*
Types
 */
export type ProgramRoundStrategy =
    | 'noRound'
    | 'threeDigits'
    | 'twoDigits'
    | 'oneDigit'
    | 'fiveDigits'
    | 'firstMeaningDigit';
export type SegmentType =
    | 'md'
    | 'computational'
    | 'latex'
    | 'asciimath'
    | 'empty';

// Viewer/Project display mode for result rendering
export type ProjectType = 'markdown' | 'latex';
export type StatementType =
    | 'assignment'
    | 'calculation'
    | 'file'
    | 'table'
    | 'plot'
    | 'latex'
    | 'no_result';
export type PlotType = 'line' | 'scatter' | 'histogram' | 'dotted';
export type OpenParams = 'login' | 'ai' | 'latex' | 'markdown';

/*
Domain
 */
export interface UserInfo {
    email: string;
    id: number;
    isAuthenticated: boolean;
    privacyPolicyAccepted: boolean;
    tokenBalance: number;
}

export interface LabkeeperFile {
    autogenerated: boolean;
    fileName: string;
    url: string;
}

export interface Segment {
    type: SegmentType;
    parameters: {
        visible?: boolean;
        hideAssignment?: boolean;
        hideAssignmentWithValues?: boolean;
        hideValue?: boolean;
        hideGeneralFormula?: boolean;
        hideInflAssignment?: boolean;
        hideInflAssignmentWithValues?: boolean;
        hideInfl?: boolean;
    };
    text: string;
}

export interface CompileSuccessResult {
    segments: OutputSegment[];
}

export interface OutputSegment {
    type: SegmentType;
}

export interface ComputationalOutputSegment extends OutputSegment {
    statements: Statement[];
    type: 'computational';
}

export interface TextOutputSegment extends OutputSegment {
    text: string;
    type: 'md' | 'latex' | 'asciimath';
}

export interface Statement {
    type: StatementType;
}

export interface ProgramParameters {
    roundStrategy: ProgramRoundStrategy;
}

export interface Program {
    segments: Segment[];
    parameters: ProgramParameters;
}

export interface Project {
    projectId: string;
    userId: number;
    title: string;
    lastModified: string;
    program: Program;
    isPublic: boolean;
    projectType: ProjectType;
}

export interface ProjectShort {
    projectId: string;
    userId: number;
    title: string;
    lastModified: string;
}

export enum CompileError {
    // TOKENIZER
    CODE_NO_END_QUOTES = 100,
    UNKNOWN_SYMBOL = 102,
    QUOTA_EXCEEDED = 103,

    // PARSER
    OPERATOR_EXPECTED = 202,
    NUMBER_EXPECTED = 203,
    NAME_EXPECTED = 204,
    NAME_RESERVED = 205,

    // INTERPRETER
    NO_SUCH_VARIABLE = 301,
    ARITHMETIC_ERROR = 305,
    CANCELED = 306,
    NOT_ENOUGH_WORKERS = 307,
    FILE_USAGE_NOT_ALLOWED = 308,
    TOO_MUCH_FILES = 310,
    INCORRECT_INFL_DEFINITION_ARRAY_SIZE = 311,
    INCORRECT_INFL_DEFINITION_VALUE_WITH_INFL = 312,
    ARRAY_HAVE_ONLY_ZERO_VALUES = 313,

    // FUNCTIONS
    INCORRECT_ARGUMENT_SIZE = 401,
    INCORRECT_ARGUMENTS_COUNT = 402,
    INCORRECT_ARGUMENT = 403,
    STRING_ARGUMENT_EXPECTED = 302,
    ARRAY_ARGUMENT_EXPECTED = 303,
    NO_SUCH_FUNCTION = 304,
    FUNCTION_HAS_NO_RETURN_VALUE = 407,

    // MD
    VARIABLE_INSERT_ERROR = 501,

    // OTHER
    MULTIPLE_ERROR = 600,
    LOGIN_REQUIRED = 7777, // USED ONLY AT FRONTEND

    // Latex
    LATEX_ERROR = 700,
}

export interface CalcStatement extends Statement {
    array?: { array: { value: number; infl: number }[] };
    assignment?: string;
    assignmentWithValues?: string[];
    inflAssignment?: string;
    inflAssignmentGeneralFormula?: string;
    inflAssignmentWithValues?: string[];
    variable: string;
    type: 'calculation';
}

export interface LatexStatement extends Statement {
    latex: string;
    type: 'latex';
}

export interface PlotStatement extends Statement {
    plotName: string;
    plotXAxisName: string;
    plotYAxisName: string;
    plots: PlotDto[];
    legendVisible: boolean;
    type: 'plot';
    plotGridVisible?: boolean;
}

export interface FileStatement extends Statement {
    url: string;
    type: 'file';
}

export interface TableStatement extends Statement {
    items: string[][];
    type: 'table';
}

export interface PlotDto {
    x: number[];
    y: number[];
    name: string;
    type: PlotType;
    color: string;
    xInfl: number[];
    yInfl: number[];
    size?: number;
}

export interface CompileErrorResultList {
    errors: CompileErrorResult[];
    unfinishedPdfUri?: string;
}

export interface CompileErrorResult {
    code: CompileError;
    payload: {
        line: number;
        position: number;
        segmentId: number | null;
    };
}

export interface QuotaPayload {
    limit: string;
    quotaIndex: number;
    value: string;
}

export interface NoSuchVariablePayload {
    variable: string;
}

export interface LatexErrorPayload {
    latexErrorMessage: string;
}

export interface FunctionErrorPayload {
    functionName: string;
}

export interface OperatorExcepctedpayload {
    operators: string[];
}
