import {
    MockViewModelRepository,
    mockViewModelState,
    ViewModelRepository,
} from '../../viewModel/repository';
import { mockRpi, RequestResult, RichProject, Rpi } from '../../model/rpi';
import {
    mockObserver,
    ObserverService,
} from '../../model/service/ObserverService.ts';
import { setupContext } from '../../viewModel/context.ts';
import { LabkeeperFile } from '../../model/domain.ts';

export const USER_ID = 111;
export const USER_EMAIL = 'a@gmail.com';
export const PROJECT_ID = '2cd18704-6c3f-48cb-96f1-9a923930f8cb';
export const PROJECT_TITLE = 'biba project';
export const FILE_NAME = 'myfile.txt';
export const FILE_URL =
    'https://files.labkeeper.io/project/348484/user/43444/myfile.txt';
export const DEFAULT_INSTANT: Date = new Date('2025-09-08T12:15:38.514Z');

global.structuredClone = (val) => {
    if (val === undefined) {
        return undefined;
    }
    return JSON.parse(JSON.stringify(val));
};

export const mockContext = () => {
    const mvs = mockViewModelState();
    const rpi: Rpi = mockRpi();
    const observerService: ObserverService = mockObserver();

    return setupContext(rpi, mvs, observerService);
};

export function mockUserInfoWithDefaultUser(rpi: Rpi) {
    rpi.getUserInfoRequest = jest.fn().mockResolvedValue({
        code: 200,
        body: {
            isAuthenticated: true,
            email: USER_EMAIL,
            id: USER_ID,
            tokens: 0,
        },
        isOk: true,
        isUnauth: false,
        isForbidden: false,
    });
}

export function mockUserInfoForUnauthorized(rpi: Rpi) {
    rpi.getUserInfoRequest = jest.fn().mockResolvedValue({
        code: 200,
        body: {
            isAuthenticated: false,
            email: '',
            id: 0,
            tokens: 0,
        },
        isOk: true,
        isUnauth: false,
        isForbidden: false,
    });
}

export function mockS3LabsFileForDefaultLab(rpi: Rpi) {
    rpi.getS3FileRequest = jest.fn().mockResolvedValue({
        code: 200,
        body: {
            labs: [
                { name: 'biba', link: 'https://labkeeper.io/project/244383' },
            ],
        },
        isOk: true,
        isUnauth: false,
        isForbidden: false,
    });
}

export function mockDefaultProjectRequestWithDefaultProject(rpi: Rpi) {
    rpi.getDefaultProjectRequest = jest.fn().mockResolvedValue({
        code: 200,
        isOk: true,
        isUnauth: false,
        isForbidden: false,
        body: {
            projectId: PROJECT_ID,
            userId: USER_ID,
            title: PROJECT_TITLE,
            lastProgramResult: undefined,
            lastModified: DEFAULT_INSTANT.toISOString(),
            isPublic: false,
            program: {
                segments: [],
                parameters: {
                    roundStrategy: 'noRound',
                },
            },
            projectType: 'markdown',
        },
    } as RequestResult<RichProject>);
}

export function mockGetProjectRequestWithDefaultProject(rpi: Rpi) {
    rpi.getProjectRequest = jest.fn().mockResolvedValue({
        code: 200,
        isOk: true,
        isUnauth: false,
        isForbidden: false,
        body: {
            projectId: PROJECT_ID,
            userId: USER_ID,
            title: PROJECT_TITLE,
            lastProgramResult: undefined,
            lastModified: DEFAULT_INSTANT.toISOString(),
            isPublic: false,
            program: {
                segments: [],
                parameters: {
                    roundStrategy: 'noRound',
                },
            },
            projectType: 'markdown',
        },
    } as RequestResult<RichProject>);
}

export function mockGetAllProjectsRequestWithDefaultProject(rpi: Rpi) {
    rpi.getAllProjectsRequest = jest.fn().mockResolvedValue({
        code: 200,
        isOk: true,
        isUnauth: false,
        isForbidden: false,
        body: {
            projects: [
                {
                    projectId: PROJECT_ID,
                    userId: USER_ID,
                    title: PROJECT_TITLE,
                    lastModified: DEFAULT_INSTANT.toISOString(),
                    isPublic: false,
                },
            ],
        },
    });
}

export function mockListFilesRequestWithDefaultFile(rpi: Rpi) {
    rpi.listFilesRequest = jest.fn().mockResolvedValue({
        code: 200,
        isOk: true,
        isUnauth: false,
        isForbidden: false,
        body: {
            files: [
                {
                    autogenerated: false,
                    fileName: FILE_NAME,
                    url: FILE_URL,
                } as LabkeeperFile,
            ],
        },
    });
}

export function matchRepositorySnapshot(repository: ViewModelRepository) {
    expect(
        (repository as MockViewModelRepository).mockState()
    ).toMatchSnapshot();
}

export function mockSaveProgramRequest(rpi: Rpi) {
    rpi.saveProgramRequest = jest.fn().mockResolvedValue({
        code: 200,
        isOk: true,
        isUnauth: false,
        isForbidden: false,
        body: {},
    });
}

export function mockAuthenticatedStartup(rpi: Rpi) {
    mockUserInfoWithDefaultUser(rpi);
    mockDefaultProjectRequestWithDefaultProject(rpi);
    mockGetProjectRequestWithDefaultProject(rpi);
    mockGetAllProjectsRequestWithDefaultProject(rpi);
    mockListFilesRequestWithDefaultFile(rpi);
}
